"""add receipt user to help link assignments

Revision ID: 1954b05ce143
Revises: eefce0f5bb5e
Create Date: 2026-01-24 10:57:46.620772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1954b05ce143'
down_revision = 'eefce0f5bb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create receipt_users table
    op.create_table('receipt_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_users_deleted_at'), ['deleted_at'], unique=False)

    # Step 2: Add receipt_user_id column as nullable first
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_user_id', sa.BigInteger(), nullable=True))

    # Step 3: Data migration - create receipt_users and link assignments
    conn = op.get_bind()
    
    # 3a. Create receipt_users for assignments with user_id
    # Use DISTINCT ON to get one receipt_user per user_id, preferring assignment display_name
    # but falling back to user's display_name from users table
    conn.execute(sa.text("""
        INSERT INTO receipt_users (user_id, display_name)
        SELECT DISTINCT ON (a.user_id) a.user_id, COALESCE(a.display_name, u.display_name)
        FROM assignments a
        LEFT JOIN users u ON a.user_id = u.id
        WHERE a.user_id IS NOT NULL
        ORDER BY a.user_id, a.display_name NULLS LAST
    """))
    
    # 3b. Create receipt_users for anonymous assignments (display_name only)
    conn.execute(sa.text("""
        INSERT INTO receipt_users (display_name)
        SELECT DISTINCT display_name 
        FROM assignments 
        WHERE user_id IS NULL AND display_name IS NOT NULL
    """))
    
    # 3c. Update assignments to point to receipt_users (for user_id matches)
    conn.execute(sa.text("""
        UPDATE assignments a
        SET receipt_user_id = ru.id
        FROM receipt_users ru
        WHERE a.user_id = ru.user_id AND a.user_id IS NOT NULL
    """))
    
    # 3d. Update assignments to point to receipt_users (for display_name only)
    conn.execute(sa.text("""
        UPDATE assignments a
        SET receipt_user_id = ru.id
        FROM receipt_users ru
        WHERE a.user_id IS NULL 
          AND a.display_name = ru.display_name 
          AND ru.user_id IS NULL
    """))
    
    # Step 4: Now make receipt_user_id NOT NULL and complete schema changes
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('receipt_user_id', nullable=False)
        batch_op.drop_index('ix_assignments_user_id')
        batch_op.create_index(batch_op.f('ix_assignments_receipt_user_id'), ['receipt_user_id'], unique=False)
        batch_op.drop_constraint('assignments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'receipt_users', ['receipt_user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('display_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add back user_id and display_name columns
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=True))
    
    # Step 2: Restore data from receipt_users to assignments
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE assignments a
        SET user_id = ru.user_id,
            display_name = ru.display_name
        FROM receipt_users ru
        WHERE a.receipt_user_id = ru.id
    """))
    
    # Step 3: Drop foreign key and index for receipt_user_id, then drop the column
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_assignments_receipt_user_id'))
        batch_op.drop_column('receipt_user_id')
    
    # Step 4: Create the old foreign key and index for user_id
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_foreign_key('assignments_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_assignments_user_id', ['user_id'], unique=False)

    # Step 5: Drop receipt_users table
    with op.batch_alter_table('receipt_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_users_deleted_at'))

    op.drop_table('receipt_users')
    # ### end Alembic commands ###
