"""Make quantity, price_per_item, and total_price non-nullable in receipt_line_items

Revision ID: 1efc3c2f07fd
Revises: 5957cab56ec6
Create Date: 2025-08-25 10:38:34.814826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efc3c2f07fd'
down_revision = '5957cab56ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user_receipts')
    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price_per_item',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('price_per_item',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_user_receipts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_receipt', sa.BOOLEAN(), nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('merchant', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('subtotal', sa.FLOAT(), nullable=True),
    sa.Column('tax', sa.FLOAT(), nullable=True),
    sa.Column('tip', sa.FLOAT(), nullable=True),
    sa.Column('gratuity', sa.FLOAT(), nullable=True),
    sa.Column('total', sa.FLOAT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=120), nullable=True),
    sa.Column('tax_included_in_items', sa.BOOLEAN(), nullable=True),
    sa.Column('display_subtotal', sa.FLOAT(), nullable=True),
    sa.Column('items_total', sa.FLOAT(), nullable=True),
    sa.Column('pretax_total', sa.FLOAT(), nullable=True),
    sa.Column('posttax_total', sa.FLOAT(), nullable=True),
    sa.Column('final_total', sa.FLOAT(), nullable=True),
    sa.Column('carrier', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ticket_number', sa.VARCHAR(length=255), nullable=True),
    sa.Column('origin', sa.VARCHAR(length=255), nullable=True),
    sa.Column('destination', sa.VARCHAR(length=255), nullable=True),
    sa.Column('passenger', sa.VARCHAR(length=255), nullable=True),
    sa.Column('class', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fare', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('taxes', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
