"""create assignments table

Revision ID: 33e3751fc7f1
Revises: 9351c43727f0
Create Date: 2026-01-19 21:54:08.596704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '33e3751fc7f1'
down_revision = '9351c43727f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('receipt_line_item_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receipt_line_item_id'], ['receipt_line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_receipt_line_item_id'), ['receipt_line_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.Text(), nullable=True))

    # ### end Alembic commands ###

    # --- Data migration: convert legacy assignments to new structure ---
    conn = op.get_bind()
    
    # Get all line items with non-empty assignments
    line_items = conn.execute(sa.text("""
        SELECT id, assignments 
        FROM receipt_line_items 
        WHERE assignments IS NOT NULL 
          AND assignments != '[]'::jsonb
          AND jsonb_array_length(assignments) > 0
    """)).fetchall()
    
    # Collect unique usernames
    username_set = set()
    for row in line_items:
        if row.assignments:
            for name in row.assignments:
                if name and isinstance(name, str):
                    username_set.add(name.strip())
    
    # Create users for each unique username
    username_to_user_id = {}
    for idx, username in enumerate(sorted(username_set), start=1):
        auth_user_id = f"assignments-migration-user-{idx}"
        result = conn.execute(sa.text("""
            INSERT INTO users (auth_user_id, username, display_name)
            VALUES (:auth_user_id, :username, :display_name)
            RETURNING id
        """), {
            'auth_user_id': auth_user_id,
            'username': username,
            'display_name': username,
        })
        user_id = result.fetchone()[0]
        username_to_user_id[username] = user_id
    
    # Create assignment records
    for row in line_items:
        if row.assignments:
            for name in row.assignments:
                if name and isinstance(name, str):
                    name = name.strip()
                    if name in username_to_user_id:
                        conn.execute(sa.text("""
                            INSERT INTO assignments (user_id, receipt_line_item_id)
                            VALUES (:user_id, :line_item_id)
                        """), {
                            'user_id': username_to_user_id[name],
                            'line_item_id': row.id,
                        })


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete migrated users (before dropping assignments table due to FK)
    conn = op.get_bind()
    conn.execute(sa.text("""
        DELETE FROM users 
        WHERE auth_user_id LIKE 'assignments-migration-user-%'
    """))
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_receipt_line_item_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_deleted_at'))

    op.drop_table('assignments')
    # ### end Alembic commands ###
