"""add indexes for users table

Revision ID: 52c4c01864ca
Revises: 2de705d110e9
Create Date: 2026-01-04 23:13:56.561157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c4c01864ca'
down_revision = '2de705d110e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_auth_user_id', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_auth_user_id'), ['auth_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_auth_user_id'))
        batch_op.create_unique_constraint('uq_users_auth_user_id', ['auth_user_id'])

    # ### end Alembic commands ###
