"""Change assignments field from Text to JSON type

Revision ID: 53dbed776d5e
Revises: 464229cd9846
Create Date: 2025-08-23 16:50:20.203070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53dbed776d5e'
down_revision = '464229cd9846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.alter_column('assignments',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.alter_column('assignments',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
