"""Add ON DELETE CASCADE to receipt_line_items.receipt_id foreign key

Revision ID: 5d1f2ea1bc48
Revises: 1efc3c2f07fd
Create Date: 2025-08-25 11:16:54.599894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1f2ea1bc48'
down_revision = '1efc3c2f07fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to recreate the table to modify foreign key constraints
    # First, create a new table with the correct foreign key constraint
    op.execute('''
        CREATE TABLE receipt_line_items_new (
            id VARCHAR(36) NOT NULL,
            receipt_id INTEGER NOT NULL,
            name VARCHAR(255),
            quantity INTEGER NOT NULL,
            price_per_item NUMERIC(12, 2) NOT NULL,
            total_price NUMERIC(12, 2) NOT NULL,
            assignments JSON,
            created_at DATETIME DEFAULT (datetime('now')),
            PRIMARY KEY (id),
            FOREIGN KEY(receipt_id) REFERENCES user_receipts(id) ON DELETE CASCADE
        )
    ''')
    
    # Copy data from old table to new table
    op.execute('INSERT INTO receipt_line_items_new SELECT * FROM receipt_line_items')
    
    # Drop old table and rename new table
    op.drop_table('receipt_line_items')
    op.execute('ALTER TABLE receipt_line_items_new RENAME TO receipt_line_items')
    
    # Create index on receipt_id
    op.create_index(op.f('ix_receipt_line_items_receipt_id'), 'receipt_line_items', ['receipt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the table without CASCADE
    op.execute('''
        CREATE TABLE receipt_line_items_old (
            id VARCHAR(36) NOT NULL,
            receipt_id INTEGER NOT NULL,
            name VARCHAR(255),
            quantity INTEGER NOT NULL,
            price_per_item NUMERIC(12, 2) NOT NULL,
            total_price NUMERIC(12, 2) NOT NULL,
            assignments JSON,
            created_at DATETIME DEFAULT (datetime('now')),
            PRIMARY KEY (id),
            FOREIGN KEY(receipt_id) REFERENCES user_receipts(id)
        )
    ''')
    
    # Copy data back
    op.execute('INSERT INTO receipt_line_items_old SELECT * FROM receipt_line_items')
    
    # Drop new table and rename old table
    op.drop_table('receipt_line_items')
    op.execute('ALTER TABLE receipt_line_items_old RENAME TO receipt_line_items')
    
    # Recreate index
    op.create_index(op.f('ix_receipt_line_items_receipt_id'), 'receipt_line_items', ['receipt_id'], unique=False)

    # ### end Alembic commands ###
