"""add share_percentage and locked to assignments

Revision ID: 76997c37f508
Revises: d67f07100e72
Create Date: 2026-04-19 20:44:11.179008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76997c37f508'
down_revision = 'd67f07100e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_percentage', sa.Numeric(precision=7, scale=4), nullable=True))
        batch_op.add_column(sa.Column('locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('locked')
        batch_op.drop_column('share_percentage')

    # ### end Alembic commands ###
