"""add auth_user_id and soft delete support

Revision ID: 8bfcfcba9e52
Revises: 6cc783342a7a
Create Date: 2026-01-04 21:07:08.088066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfcfcba9e52'
down_revision = '6cc783342a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('auth_user_id', sa.Text(), nullable=True))
    
    # Soft delete existing users and set placeholder auth_user_id
    op.execute("UPDATE users SET deleted_at = CURRENT_TIMESTAMP WHERE deleted_at IS NULL")
    op.execute("UPDATE users SET auth_user_id = 'legacy_user_' || id::text WHERE auth_user_id IS NULL")
    
    # Now make auth_user_id NOT NULL and add unique constraint
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('auth_user_id', nullable=False)
        batch_op.create_unique_constraint('uq_users_auth_user_id', ['auth_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_auth_user_id', type_='unique')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('auth_user_id')

    # ### end Alembic commands ###
