"""add original_tip to user_receipts

Revision ID: 8d6982a3f40c
Revises: f4546f715c43
Create Date: 2026-03-21 21:37:59.257634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6982a3f40c'
down_revision = 'f4546f715c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_tip', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###

    # Data migration: copy existing tip values to original_tip
    user_receipts = sa.table('user_receipts',
        sa.column('tip', sa.Numeric(12, 2)),
        sa.column('original_tip', sa.Numeric(12, 2)),
    )
    op.execute(
        user_receipts.update().values(original_tip=user_receipts.c.tip)
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_receipts', schema=None) as batch_op:
        batch_op.drop_column('original_tip')

    # ### end Alembic commands ###
