"""Add image_visibility to user_receipts

Revision ID: 9351c43727f0
Revises: 52c4c01864ca
Create Date: 2026-01-10 23:52:23.258016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9351c43727f0'
down_revision = '52c4c01864ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default to handle existing rows
    with op.batch_alter_table('user_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_visibility', sa.Text(), nullable=False, server_default='public'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_receipts', schema=None) as batch_op:
        batch_op.drop_column('image_visibility')

    # ### end Alembic commands ###
