"""Drop legacy assignments column from receipt_line_items

Revision ID: bf5172c3b17b
Revises: f4581a533603
Create Date: 2026-03-07 20:02:41.427430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf5172c3b17b'
down_revision = 'f4581a533603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.drop_column('assignments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
