"""initial sqlite schema

Revision ID: d46372914063
Revises: 
Create Date: 2025-09-02 00:51:52.388811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46372914063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_receipt', sa.Boolean(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tip', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gratuity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=120), nullable=True),
    sa.Column('tax_included_in_items', sa.Boolean(), nullable=True),
    sa.Column('display_subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('items_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pretax_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('posttax_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('carrier', sa.String(length=255), nullable=True),
    sa.Column('ticket_number', sa.String(length=255), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('passenger', sa.String(length=255), nullable=True),
    sa.Column('class', sa.String(length=50), nullable=True),
    sa.Column('fare', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_item', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('assignments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['user_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_line_items_receipt_id'), ['receipt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_line_items_receipt_id'))

    op.drop_table('receipt_line_items')
    op.drop_table('user_receipts')
    op.drop_table('users')
    # ### end Alembic commands ###
