"""add original_tax to user_receipts

Revision ID: d67f07100e72
Revises: a1b2c3d4e5f6
Create Date: 2026-04-17 12:30:59.479768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67f07100e72'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_tax', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###

    # Data migration: copy existing tax values to original_tax
    user_receipts = sa.table('user_receipts',
        sa.column('tax', sa.Numeric(12, 2)),
        sa.column('original_tax', sa.Numeric(12, 2)),
    )
    op.execute(
        user_receipts.update().values(original_tax=user_receipts.c.tax)
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_receipts', schema=None) as batch_op:
        batch_op.drop_column('original_tax')

    # ### end Alembic commands ###
