"""Remove receipt_data column from user_receipts table

Revision ID: d91acbfc8ad6
Revises: 2cb916bbb47d
Create Date: 2025-08-24 00:59:48.831568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91acbfc8ad6'
down_revision = '2cb916bbb47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_receipts', schema=None) as batch_op:
        batch_op.drop_column('receipt_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_data', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
