"""anon-y assignments

Revision ID: eefce0f5bb5e
Revises: 33e3751fc7f1
Create Date: 2026-01-24 08:41:43.083506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefce0f5bb5e'
down_revision = '33e3751fc7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_receipt_line_items_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('receipt_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_line_items_deleted_at'))
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
