"""add tip_after_tax to user_receipts

Revision ID: f4546f715c43
Revises: bf5172c3b17b
Create Date: 2026-03-08 21:57:27.251837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4546f715c43'
down_revision = 'bf5172c3b17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tip_after_tax', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_receipts', schema=None) as batch_op:
        batch_op.drop_column('tip_after_tax')

    # ### end Alembic commands ###
